#baseurl: "http://fanyingjie.com/"
baseurl: "http://localhost:1313/"
languageCode: "en-us"
title: "fyj的个人网站"
theme: "hugo-ivy"
googleAnalytics: "UA-1988641-2"
#disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"
rssLimit: 100

permalinks:
  cn: "/cn/:year/:month/:slug/"
  en: "/en/:year/:month/:slug/"


menu:
  main:
    - name: "About"
      url: "/en/about/"
      weight: 1
    - name: "Blog"
      url: "/en/"
      weight: 2
    - name: "Categories"
      url: "/categories/"
      weight: 3    
    - name: "Tags"
      url: "/tags/"
      weight: 4       
    - name: "关于"
      url: "/cn/about/"
      weight: 5
    - name: "博客"
      url: "/cn/"
      weight: 6
  en:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/en/about/"
      weight: 2
    - name: "Blog"
      url: "/en/"
      weight: 3
    - name: "Categories"
      url: "/categories/"
      weight: 4   
    - name: "Tags"
      url: "/tags/"
      weight: 5
    - name: "中文"
      url: "/cn/"
      weight: 6
  cn:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "关于"
      url: "/cn/about/"
      weight: 2
    - name: "博客"
      url: "/cn/"
      weight: 3
    - name: "分类"
      url: "/categories/"
      weight: 4   
    - name: "标签"
      url: "/tags/"
      weight: 5
    - name: "English"
      url: "/en/"
      weight: 6
  

params:
  description: "Personal website of fyj"
  footer: "&copy; 2019 [fyj](/) [京ICP备19023380号](http://www.beian.miit.gov.cn)"
  #disqusURL: ""
  customJS:
    - "js/fix-toc.js"
    - "js/center-img.js"
    - "js/right-quote.js"
    - "js/no-highlight.js"
    - "js/fix-footnote.js"
    - "js/math-code.js"
    - "js/external-link.js"
    - "js/alt-title.js"
    - "js/header-link.js"
 # githubContentURL: ""
 # twitterImage: "/images/logo.png"

  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion: "9.12.0"
  highlightjsCDN: "//cdn.bootcss.com"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"

  logo:
    en:
      img: "/images/logo.png"
      url: "/"
      alt: ""
      tag: ""


  author:
    en: "fyj"
    cn: "fyj"

  #lang:
  #  edit:
  #    cn: "编辑"
  #  license:
  #    cn: "版权"
  #  subscribe:
#    cn: "订阅"

blackfriday:
    extensionsmask: ["noIntraEmphasis"]
    fractions: false
